repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      -  id: fix-byte-order-marker
      -  id: check-json
      -  id: check-merge-conflict
      -  id: detect-aws-credentials
      -  id: end-of-file-fixer

  - repo: local
    hooks:
      - id: black
        name: Python Black
        entry: poetry -P ./worker run black
        require_serial: true
        language: system
        types: [python]

      - id: flake8
        name: Python Flake8
        entry: poetry -P ./worker run flake8 --toml-config ./worker/pyproject.toml
        require_serial: true
        language: system
        types: [python]

      - id: isort
        name: Python isort
        entry: poetry -P ./worker run isort
        require_serial: true
        language: system
        types: [python]

      - id: mypy
        name: Python Typing (mypy) strict
        entry: poetry -P ./worker run mypy --follow-imports=silent
        require_serial: true
        language: system
        types: [python]
